using System.Collections;
using UnityEngine;
using System.Linq;
public class EnemyMovement : MonoBehaviour
{
    [SerializeField] float speed = 3f;
    [SerializeField] float rotationSpeed = 5f;
    [SerializeField] private float dashSpeed = 10f;
    [SerializeField] float chasingMaxDistance = 15f;
    [SerializeField] float playerChaseDistance = 3f;

    private Transform player;
    private Vector3 targetPosition;
    private Vector3 dashTarget;
    private bool isChasing = false;
    private bool isDashing = false;
    private Transform rangeA;
    private Transform rangeB;

    private LayerMask collisionLayer;
    private Vector3 ChasingRandomPosition;

    public EnemyManagement enemyManagement;
    private EnemyBase enemyBase;

    private void Start()
    {
        rangeA = GameObject.Find("ChaseRangeA").transform;
        rangeB = GameObject.Find("ChaseRangeB").transform;
        player = GameObject.FindGameObjectWithTag("Player").transform;

        enemyBase = GetComponent<EnemyBase>();

        enemyManagement = EnemyManagement.Instance;
        if (enemyManagement == null)
        {
            Debug.LogError("EnemyManager not found.");
        }

        // if (!isChasing)
        //     SetWayPoint();
        // else if (isChasing)
        //     ChasingRandomPosition = GetRandomPositionNearPlayer();
    }

    // private void Update()
    // {
    //     Vector3 direction;
    //     if (isDashing)
    //     {
    //         EnemyDash();
    //         if (!CheckDashList())
    //         {
    //             isDashing = false;
    //         }
    //     }
    //     else
    //     {
    //         if (isChasing)
    //         {
    //             if (Vector3.Distance(transform.position, ChasingRandomPosition) < 1f)
    //             {
    //                 ChasingRandomPosition = GetRandomPositionNearPlayer();
    //             }

    //             if (Vector3.Distance(transform.position, player.position) < playerChaseDistance)
    //             {
    //                 direction = (player.position - transform.position).normalized;
    //             }
    //             else
    //             {
    //                 direction = (ChasingRandomPosition - transform.position).normalized;
    //             }
    //             Quaternion targetRotation = Quaternion.LookRotation(direction);
    //             transform.rotation = Quaternion.Slerp(transform.rotation, targetRotation, Time.deltaTime * rotationSpeed);


    //             transform.Translate(Vector3.forward * speed * Time.deltaTime);
    //         }
    //         else if (!isChasing)
    //         {
    //             if (CheckDashList())
    //             {
    //                 StartDashTowardsPlayer();
    //             }

    //             else if (Vector3.Distance(transform.position, targetPosition) < 1f)
    //             {
    //                 SetWayPoint();
    //             }
    //             direction = (targetPosition - transform.position).normalized;
    //             Quaternion targetRotation = Quaternion.LookRotation(direction);
    //             transform.rotation = Quaternion.Slerp(transform.rotation, targetRotation, Time.deltaTime * rotationSpeed);
    //             transform.Translate(Vector3.forward * speed * Time.deltaTime);

    //         }
    //     }
    // }

    // private Vector3 GetRandomPositionNearPlayer()
    // {
    //     Vector3 playerPosition = player.position;
    //     Vector3 randomOffset = Random.insideUnitSphere * chasingMaxDistance;
    //     Vector3 randomposition = playerPosition + randomOffset;
    //     if (randomposition.y < 0)
    //     {
    //         randomposition.y = Mathf.Abs(randomposition.y);//ï¿½nï¿½Ê‚ï¿½è‰ºï¿½Ésï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½æ‚¤ï¿½ï¿½yï¿½ï¿½ï¿½Wï¿½ð³‚ï¿½
    //     }
    //     Collider[] colliders = Physics.OverlapSphere(randomposition, chasingMaxDistance, collisionLayer);
    //     if (colliders.Length > 0)
    //     {
    //         return GetRandomPositionNearPlayer();//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ñƒ‰ƒï¿½ï¿½_ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    //     }
    //     return randomposition;
    // }

    // private void SetWayPoint()
    // {
    //     Vector3 randomPosition = GenerateRandomPosition();
    //     Debug.Log("Random Position: " + randomPosition + this.gameObject.name);//ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½ï¿½ï¿½Wï¿½mï¿½Fï¿½p
    //     targetPosition = randomPosition;
    // }

    // private Vector3 GenerateRandomPosition()
    // {
    //     Vector3 randomDirection = Random.insideUnitSphere * wanderingDistance;
    //     randomDirection += transform.position; // ï¿½ï¿½ï¿½Ý‚ÌˆÊ’uï¿½ï¿½ï¿½Nï¿½_ï¿½É‚ï¿½ï¿½ï¿½
    //     randomDirection.y = Mathf.Abs(randomDirection.y); //ï¿½nï¿½Ê‚É–ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½ï¿½á‚¤ï¿½Ì‚ï¿½yï¿½ï¿½ï¿½Wï¿½ð³‚ï¿½

    //     // ï¿½mï¿½Fï¿½ï¿½ï¿½ï¿½ÍˆÍ‚ÌÅï¿½ï¿½lï¿½ÆÅ‘ï¿½lï¿½ï¿½ï¿½ï¿½ï¿½ß‚ï¿½
    //     Vector3 minRange = new Vector3(
    //         Mathf.Min(rangeA.position.x, rangeB.position.x),
    //         Mathf.Min(rangeA.position.y, rangeB.position.y),
    //         Mathf.Min(rangeA.position.z, rangeB.position.z)
    //     );

    //     Vector3 maxRange = new Vector3(
    //         Mathf.Max(rangeA.position.x, rangeB.position.x),
    //         Mathf.Max(rangeA.position.y, rangeB.position.y),
    //         Mathf.Max(rangeA.position.z, rangeB.position.z)
    //     );

    //     // ï¿½ÍˆÍ“ï¿½ï¿½Éƒï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½Èï¿½ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½é‚©ï¿½mï¿½Fï¿½ï¿½ï¿½ï¿½
    //     if (randomDirection.x >= minRange.x && randomDirection.x <= maxRange.x &&
    //         randomDirection.y >= minRange.y && randomDirection.y <= maxRange.y &&
    //         randomDirection.z >= minRange.z && randomDirection.z <= maxRange.z)
    //     {
    //         return randomDirection; // ï¿½ÍˆÍ“ï¿½ï¿½Ìê‡ï¿½Í‚ï¿½ï¿½Ì‚Ü‚Ü•Ô‚ï¿½
    //     }
    //     else
    //     {
    //         // ï¿½ÍˆÍŠOï¿½Ìê‡ï¿½ÍÄ“xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    //         return GenerateRandomPosition();
    //     }
    // }

    // private bool CheckDashList()
    // {
    //     return enemyBase.getEnemyType == EnemyType.dash;
    // }

    // private void StartDashTowardsPlayer()
    // {
    //     isDashing = true;
    //     dashTarget = player.position;
    //     Debug.Log("ï¿½_ï¿½bï¿½Vï¿½ï¿½ï¿½Ú“Iï¿½n" + dashTarget + this.gameObject.name);
    // }

    // private void EnemyDash()
    // {
    //     Vector3 direction = (dashTarget - transform.position).normalized;
    //     Quaternion targetRotation = Quaternion.LookRotation(direction);
    //     transform.rotation = Quaternion.Slerp(transform.rotation, targetRotation, Time.deltaTime * rotationSpeed);
    //     transform.Translate(Vector3.forward * dashSpeed * Time.deltaTime);

    //     if (Vector3.Distance(transform.position, dashTarget) < 1.0f)
    //     {
    //         isDashing = false;
    //         //enemyManagement.dashList.Remove(this.gameObject);
    //         enemyBase._enemyState = EnemyState.wander;
    //     }
    // }


    // public void EnemyChaseSetActive()//EnemySpawnï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚Ñoï¿½ï¿½ï¿½Ä’ÇÕƒï¿½ï¿½[ï¿½htrueï¿½É‚ï¿½ï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Ä‚ï¿½Â‚Å‚ï¿½ï¿½B
    // {
    //     isChasing = true;
    //     //Debug.Log("Active!" + isChasing);
    // }
}
